# Generated by Django 2.2.28 on 2023-09-16 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustommodel',
            name='Рефералка при регистрации',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usercustommodel',
            name='Реферальный код',
            field=models.CharField(default='bhrrgolj', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='usercustommodel',
            name='Скидка',
            field=models.IntegerField(default=0),
        ),
    ]
