# Generated by Django 2.2.28 on 2023-09-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0004_auto_20230916_1924'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercustommodel',
            old_name='Регистрация',
            new_name='Пароль',
        ),
        migrations.AlterField(
            model_name='usercustommodel',
            name='Количество доступных сообщений',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='usercustommodel',
            name='Реферальный код',
            field=models.CharField(default='wpagpaqj', max_length=8, unique=True),
        ),
    ]
