# Generated by Django 2.2.28 on 2023-09-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0007_auto_20230916_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='Цена',
            field=models.CharField(choices=[('C1', 'Цена1'), ('C2', 'Цена2'), ('C3', 'Цена3')], max_length=2),
        ),
        migrations.AlterField(
            model_name='usercustommodel',
            name='Реферальный код',
            field=models.CharField(default='ytpsjeup', max_length=8, unique=True),
        ),
    ]
