# Generated by Django 2.2.28 on 2023-09-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0008_auto_20230916_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='Количество сообщений',
            field=models.CharField(blank=True, choices=[('M1', 'Кол-во1'), ('M2', 'Кол-во2'), ('M3', 'Кол-во3')], max_length=2),
        ),
        migrations.AlterField(
            model_name='usercustommodel',
            name='Реферальный код',
            field=models.CharField(default='vrtldeot', max_length=8, unique=True),
        ),
    ]
