# Generated by Django 2.2.28 on 2023-09-16 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0010_auto_20230916_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustommodel',
            name='rate',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Тариф', to='guide.Rate'),
        ),
        migrations.AlterField(
            model_name='usercustommodel',
            name='Реферальный код',
            field=models.CharField(default='tznscimx', max_length=8, unique=True),
        ),
    ]
