# Generated by Django 2.2.28 on 2023-09-16 18:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0011_auto_20230916_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustommodel',
            name='Дата платежа',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='usercustommodel',
            name='Реферальный код',
            field=models.CharField(default='oouqgovp', max_length=8, unique=True),
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Сумма', models.IntegerField()),
                ('Дата платежа', models.DateTimeField(default=datetime.datetime.now)),
                ('rate', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Имя_тарифа', to='guide.Rate')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
