# Generated by Django 2.2.28 on 2023-09-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0012_auto_20230916_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustommodel',
            name='Реферальный код',
            field=models.CharField(default='dmigcazi', max_length=8, unique=True),
        ),
    ]
