# Generated by Django 2.2.28 on 2023-09-16 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0014_auto_20230916_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustommodel',
            name='Реферальный код',
            field=models.CharField(default='gzmsgkwz', max_length=8, unique=True),
        ),
    ]
