# Generated by Django 2.2.28 on 2023-09-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0016_auto_20230916_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustommodel',
            name='Слаг',
        ),
        migrations.AlterField(
            model_name='usercustommodel',
            name='Реферальный код',
            field=models.CharField(default='gbwyuwsr', max_length=8, unique=True),
        ),
    ]
