# Generated by Django 2.2.28 on 2023-09-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0017_auto_20230916_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustommodel',
            name='Логин',
        ),
        migrations.AlterField(
            model_name='usercustommodel',
            name='Реферальный код',
            field=models.CharField(default='adqotjmx', max_length=8, unique=True),
        ),
    ]
