# Generated by Django 2.2.28 on 2023-09-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0019_auto_20230916_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustommodel',
            name='Реферальный код',
            field=models.CharField(default='htuoprnk', max_length=8, unique=True),
        ),
    ]
