# Generated by Django 2.2.28 on 2023-09-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0020_auto_20230916_2226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercustommodel',
            name='Реферальный код',
        ),
        migrations.AddField(
            model_name='usercustommodel',
            name='ref_code',
            field=models.CharField(default='ljonxkpk', max_length=8, unique=True),
        ),
    ]
