# Generated by Django 2.2.28 on 2023-09-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0021_auto_20230916_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustommodel',
            name='ref_code',
            field=models.CharField(default='vkochxvj', max_length=8),
        ),
    ]
