# Generated by Django 2.2.28 on 2023-09-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0022_auto_20230916_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercustommodel',
            old_name='Рефералка',
            new_name='ref',
        ),
        migrations.AlterField(
            model_name='usercustommodel',
            name='ref_code',
            field=models.CharField(default='ebqyywtd', max_length=8),
        ),
    ]
