# Generated by Django 2.2.28 on 2023-09-16 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0023_auto_20230916_2316'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercustommodel',
            old_name='Рефералка при регистрации',
            new_name='ref_signUp',
        ),
        migrations.AlterField(
            model_name='usercustommodel',
            name='ref_code',
            field=models.CharField(default='xtkogtuc', max_length=8),
        ),
    ]
