# Generated by Django 2.2.28 on 2023-09-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0024_auto_20230916_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercustommodel',
            old_name='Скидка',
            new_name='discount',
        ),
        migrations.AlterField(
            model_name='usercustommodel',
            name='ref_code',
            field=models.CharField(default='htbaoifq', max_length=8),
        ),
    ]
