# Generated by Django 2.2.28 on 2023-09-16 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0027_auto_20230916_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='Количество сообщений',
            field=models.IntegerField(blank=True, choices=[('M1', 10), ('M2', 15), ('M3', 20)], max_length=2),
        ),
        migrations.AlterField(
            model_name='rate',
            name='Название тарифа',
            field=models.CharField(choices=[('R1', 'Минимальный'), ('R2', 'Средний'), ('R3', 'Максимальный')], max_length=2),
        ),
        migrations.AlterField(
            model_name='rate',
            name='Цена',
            field=models.IntegerField(choices=[('C1', 100), ('C2', 200), ('C3', 300)], max_length=2),
        ),
        migrations.AlterField(
            model_name='usercustommodel',
            name='ref_code',
            field=models.CharField(default='ekefvgqr', max_length=8),
        ),
    ]
