# Generated by Django 2.2.28 on 2023-09-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0028_auto_20230917_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='Количество сообщений',
            field=models.IntegerField(blank=True, choices=[('M1', 10), ('M2', 15), ('M3', 20)]),
        ),
        migrations.AlterField(
            model_name='rate',
            name='Цена',
            field=models.IntegerField(choices=[('C1', 100), ('C2', 200), ('C3', 300)]),
        ),
        migrations.AlterField(
            model_name='usercustommodel',
            name='ref_code',
            field=models.CharField(default='cxnuhwse', max_length=8),
        ),
    ]
