# Generated by Django 2.2.28 on 2023-09-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0032_auto_20230917_0019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Текст сообщения',
            new_name='msg',
        ),
        migrations.RenameField(
            model_name='pay',
            old_name='Дата платежа',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='usercustommodel',
            name='ref_code',
            field=models.CharField(default='kgafkjqa', max_length=8),
        ),
    ]
