# Generated by Django 2.2.28 on 2023-09-16 21:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0034_auto_20230917_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='date_create',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='usercustommodel',
            name='ref_code',
            field=models.CharField(default='fjegmuuu', max_length=8),
        ),
    ]
