# Generated by Django 2.2.28 on 2023-09-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0035_auto_20230917_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustommodel',
            name='ref_code',
            field=models.CharField(default='xgubajyk', max_length=8),
        ),
    ]
