# Generated by Django 2.2.28 on 2023-09-20 16:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0036_auto_20230917_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercustommodel',
            name='date_of_reg_ref',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='usercustommodel',
            name='ref_code',
            field=models.CharField(default='rjshrkzq', max_length=8),
        ),
    ]
