# Generated by Django 2.2.28 on 2023-09-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0037_auto_20230920_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustommodel',
            name='ref_code',
            field=models.CharField(default='esecfpie', max_length=8),
        ),
    ]
