# Generated by Django 2.2.28 on 2023-09-20 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0038_auto_20230920_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustommodel',
            name='ref_code',
            field=models.CharField(default='qxrzccte', max_length=8),
        ),
    ]
