# Generated by Django 2.2.28 on 2023-10-11 17:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0039_auto_20230920_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='session_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='from_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='отправитель', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercustommodel',
            name='ref_code',
            field=models.CharField(default='mtnbfcvo', max_length=8),
        ),
    ]
