# Generated by Django 2.2.28 on 2023-10-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0040_auto_20231011_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustommodel',
            name='ref_code',
            field=models.CharField(default='ldfhomrr', max_length=8),
        ),
    ]
