# Generated by Django 2.2.28 on 2023-10-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0041_auto_20231011_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='session_key',
            new_name='ip',
        ),
        migrations.AlterField(
            model_name='usercustommodel',
            name='ref_code',
            field=models.CharField(default='txkbzozg', max_length=8),
        ),
    ]
