# Generated by Django 2.2.28 on 2023-10-11 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0042_auto_20231011_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='ip',
            new_name='key',
        ),
        migrations.AlterField(
            model_name='usercustommodel',
            name='ref_code',
            field=models.CharField(default='ojpokupg', max_length=8),
        ),
    ]
