# Generated by Django 2.2.28 on 2023-10-13 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0043_auto_20231011_2217'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPanelEdit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(default='guide\\static\\guide\\images\x07i.png', upload_to='photos/%Y/%m/%d')),
                ('instruction', models.CharField(max_length=256)),
                ('doc', models.FileField(upload_to='files/%Y/%m/%d')),
                ('url', models.CharField(max_length=256)),
                ('token', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='to_user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='получатель', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercustommodel',
            name='ref_code',
            field=models.CharField(default='ghzpvcgo', max_length=8),
        ),
    ]
