# Generated by Django 2.2.28 on 2023-10-13 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0044_auto_20231013_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminpaneledit',
            name='avatar',
            field=models.ImageField(blank=True, default='guide\\static\\guide\\images\x07i.png', null=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='adminpaneledit',
            name='doc',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='adminpaneledit',
            name='instruction',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='adminpaneledit',
            name='token',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='adminpaneledit',
            name='url',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='usercustommodel',
            name='ref_code',
            field=models.CharField(default='tsigjtnu', max_length=8),
        ),
    ]
