# Generated by Django 2.2.28 on 2023-10-13 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0045_auto_20231013_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPiece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
            ],
        ),
        migrations.AlterField(
            model_name='adminpaneledit',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='usercustommodel',
            name='ref_code',
            field=models.CharField(default='ulitcoju', max_length=8),
        ),
    ]
