# Generated by Django 2.2.28 on 2023-10-19 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0046_auto_20231013_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='audio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usercustommodel',
            name='ref_code',
            field=models.CharField(default='dhrjlsop', max_length=8),
        ),
    ]
