# Generated by Django 2.2.28 on 2023-10-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0047_auto_20231019_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='usercustommodel',
            name='ref_code',
            field=models.CharField(default='vwvtdnxg', max_length=8),
        ),
    ]
