# Generated by Django 2.2.28 on 2023-10-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guide', '0049_auto_20231019_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercustommodel',
            name='ref_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
